# Generated by Django 3.2.8 on 2021-10-15 16:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_quotation.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=50)),
            ],
            bases=('api_quotation.basemodel',),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_quotation.basemodel')),
                ('size', models.IntegerField()),
                ('body_part', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('total_time', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            bases=('api_quotation.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api_quotation.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fk_quotation', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='api_quotation.quotation')),
            ],
            bases=('api_quotation.basemodel',),
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_quotation.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('time_cm2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('price_cm2', models.IntegerField()),
                ('fk_artist', models.ManyToManyField(to='api_quotation.Artist')),
            ],
            bases=('api_quotation.basemodel',),
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_quotation.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('fk_artist', models.ManyToManyField(to='api_quotation.Artist')),
            ],
            bases=('api_quotation.basemodel',),
        ),
        migrations.AddField(
            model_name='artist',
            name='fk_quotation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='api_quotation.quotation'),
        ),
    ]
