# Generated by Django 3.2.8 on 2021-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
