# Generated by Django 3.2.8 on 2021-10-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='time_cm2',
            field=models.ImageField(upload_to=''),
        ),
    ]
