# Generated by Django 3.2.8 on 2021-10-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_quotation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
