# Generated by Django 3.2.8 on 2021-10-14 01:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api_quotation', '0003_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_quotation.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=50)),
            ],
            bases=('api_quotation.basemodel',),
        ),
    ]
